name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: shopify-ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true

    - name: Run templating
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '14'
        check-path: 'ext'
      run: bundle exec rake templates

    - name: Run native tests
      run: make test

    - name: Run Ruby tests
      run: bundle exec rake
