name: Release

on:
  release:
    types: [created]

jobs:
  release:
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v3
        name: Use Node.js 18.x
        with:
          node-version: "18.x"
          cache: yarn

      - name: 🔨 Package
        working-directory: ./vscode
        run: |
          yarn --frozen-lockfile
          yarn run package
          echo ::set-output name=vsix_path::$(ls *.vsix)


      - name: Upload assets to release
        uses: Shopify/upload-to-release@master
        with:
          name: ${{ steps.set-vsix-path.outputs.vsix_path }}
          path: ${{ steps.set-vsix-path.outputs.vsix_path }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
